workflows:
  android-release:
    name: Build Android APK
    max_build_duration: 60
    environment:
      flutter: stable
      android: true
    scripts:
      - name: Instalar dependências
        script: flutter pub get

      - name: Build APK
        script: flutter build apk --release

    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
